/usr/bin/razor-session
/usr/bin/startrazor
/usr/bin/razor-config-session
/usr/share/applications/razor-config-session.desktop
/etc/xdg/razor/session*.conf
/etc/xdg/razor/windowmanagers.conf
/usr/share/razor/razor-session/
/usr/share/razor/razor-config-session/
/usr/share/xsessions/
/usr/share/apps/kdm/sessions/
/etc/xdg/autostart/*
/usr/share/razor/razor-confupdate/*
/usr/bin/razor-confupdate
%if MULTIARCH yes
/usr/lib/*/razor-confupdate_bin/sesion_modules
%else
/usr/lib*/razor-confupdate_bin/sesion_modules
%endif
