.TH razorqt-config "1" "September 2012" "Razor\-Qt\ 0.5.0" "Razor\-Qt\ Settings Center"
.SH NAME
razorqt-config \- Razor-qt Settings Center for all Razor-Qt related moduls and applications
.SH SYNOPSIS
.B razorqt-config
.br
.SH DESCRIPTION
This application its a desktop settings center of Razor-Qt relatd applications, and all 
config software instaled and registered by the Razor\-Qt desktop environment.
.P
Razor-Qt is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies.
.P
As new project, Razor-Qt already contains the key DE components
and can be used separately, not all of them need to be used at once:
.P
 * Panel
 * Desktop
 * Application launcher \fI(this)\fR
 * Settings center
 * Sessions
 * Polkit handler
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their name is self-descriptive.  They are usually not launched
by hand but automatically, when choosing a Razor\-Qt session in the Display
Manager.
.SH Razor Config modules
.P
Razor-QT has various config modules:ç
.P
 * Mouse settings: (\fBrazor-config-mouse\fR)
 * Desktop settings: (\fBrazor-config-desktop\fR)
 * Appereance settings: (\fBrazor-config-appearance\fR)
 * Session settings: (\fBrazor-config-session\fR)
 * Notification settings: (\fBrazor-config-notificationd\fR)
.P
All of this also can be find in Settings or Preferences menu.
.SH "REPORTING BUGS"
Report bugs to https://github.com/Razor-qt/razor-qt/issues
.SH "SEE ALSO"
Razor-Qt it has been tailored for users who value simplicity, speed, and
an intuitive interface.  Unlike most desktop environments, Razor-qt also works
fine with less powerful machines. See :
.\" any module must refers to session app, for more info on start it
.P
 * Mouse settings: \fBrazor-config-mouse.1\fR
.P
 * Desktop settings: \fBrazor-config-desktop.1\fR
.P
 * Appereance settings: \fBrazor-config-appearance.1\fR
.P
 * Session settings: \fBrazor-config-session.1\fR
.P
 * Notification settings: \fBrazor-config-notificationd.1\fR
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for Razor-Qt project and VENENUX GNU/Linux but can be used by others.
