# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(CMAKE_COMMAND) -E cmake_progress_start /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules/CMakeFiles /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules/razorqt-panel/CMakeFiles/progress.marks
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f CMakeFiles/Makefile2 razorqt-panel/all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f CMakeFiles/Makefile2 razorqt-panel/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f CMakeFiles/Makefile2 razorqt-panel/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f CMakeFiles/Makefile2 razorqt-panel/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
razorqt-panel/CMakeFiles/razor-panel.dir/rule:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f CMakeFiles/Makefile2 razorqt-panel/CMakeFiles/razor-panel.dir/rule
.PHONY : razorqt-panel/CMakeFiles/razor-panel.dir/rule

# Convenience name for target.
razor-panel: razorqt-panel/CMakeFiles/razor-panel.dir/rule
.PHONY : razor-panel

# fast build rule for target.
razor-panel/fast:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/build
.PHONY : razor-panel/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/moc_razorbar.o: src/moc_razorbar.cxx.o
.PHONY : src/moc_razorbar.o

# target to build an object file
src/moc_razorbar.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbar.cxx.o
.PHONY : src/moc_razorbar.cxx.o

src/moc_razorbar.i: src/moc_razorbar.cxx.i
.PHONY : src/moc_razorbar.i

# target to preprocess a source file
src/moc_razorbar.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbar.cxx.i
.PHONY : src/moc_razorbar.cxx.i

src/moc_razorbar.s: src/moc_razorbar.cxx.s
.PHONY : src/moc_razorbar.s

# target to generate assembly for a file
src/moc_razorbar.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbar.cxx.s
.PHONY : src/moc_razorbar.cxx.s

src/moc_razorbartask.o: src/moc_razorbartask.cxx.o
.PHONY : src/moc_razorbartask.o

# target to build an object file
src/moc_razorbartask.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbartask.cxx.o
.PHONY : src/moc_razorbartask.cxx.o

src/moc_razorbartask.i: src/moc_razorbartask.cxx.i
.PHONY : src/moc_razorbartask.i

# target to preprocess a source file
src/moc_razorbartask.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbartask.cxx.i
.PHONY : src/moc_razorbartask.cxx.i

src/moc_razorbartask.s: src/moc_razorbartask.cxx.s
.PHONY : src/moc_razorbartask.s

# target to generate assembly for a file
src/moc_razorbartask.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorbartask.cxx.s
.PHONY : src/moc_razorbartask.cxx.s

src/moc_razorclock.o: src/moc_razorclock.cxx.o
.PHONY : src/moc_razorclock.o

# target to build an object file
src/moc_razorclock.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorclock.cxx.o
.PHONY : src/moc_razorclock.cxx.o

src/moc_razorclock.i: src/moc_razorclock.cxx.i
.PHONY : src/moc_razorclock.i

# target to preprocess a source file
src/moc_razorclock.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorclock.cxx.i
.PHONY : src/moc_razorclock.cxx.i

src/moc_razorclock.s: src/moc_razorclock.cxx.s
.PHONY : src/moc_razorclock.s

# target to generate assembly for a file
src/moc_razorclock.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorclock.cxx.s
.PHONY : src/moc_razorclock.cxx.s

src/moc_razorcmd.o: src/moc_razorcmd.cxx.o
.PHONY : src/moc_razorcmd.o

# target to build an object file
src/moc_razorcmd.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorcmd.cxx.o
.PHONY : src/moc_razorcmd.cxx.o

src/moc_razorcmd.i: src/moc_razorcmd.cxx.i
.PHONY : src/moc_razorcmd.i

# target to preprocess a source file
src/moc_razorcmd.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorcmd.cxx.i
.PHONY : src/moc_razorcmd.cxx.i

src/moc_razorcmd.s: src/moc_razorcmd.cxx.s
.PHONY : src/moc_razorcmd.s

# target to generate assembly for a file
src/moc_razorcmd.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorcmd.cxx.s
.PHONY : src/moc_razorcmd.cxx.s

src/moc_razordeskswitch.o: src/moc_razordeskswitch.cxx.o
.PHONY : src/moc_razordeskswitch.o

# target to build an object file
src/moc_razordeskswitch.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razordeskswitch.cxx.o
.PHONY : src/moc_razordeskswitch.cxx.o

src/moc_razordeskswitch.i: src/moc_razordeskswitch.cxx.i
.PHONY : src/moc_razordeskswitch.i

# target to preprocess a source file
src/moc_razordeskswitch.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razordeskswitch.cxx.i
.PHONY : src/moc_razordeskswitch.cxx.i

src/moc_razordeskswitch.s: src/moc_razordeskswitch.cxx.s
.PHONY : src/moc_razordeskswitch.s

# target to generate assembly for a file
src/moc_razordeskswitch.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razordeskswitch.cxx.s
.PHONY : src/moc_razordeskswitch.cxx.s

src/moc_razorevent.o: src/moc_razorevent.cxx.o
.PHONY : src/moc_razorevent.o

# target to build an object file
src/moc_razorevent.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorevent.cxx.o
.PHONY : src/moc_razorevent.cxx.o

src/moc_razorevent.i: src/moc_razorevent.cxx.i
.PHONY : src/moc_razorevent.i

# target to preprocess a source file
src/moc_razorevent.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorevent.cxx.i
.PHONY : src/moc_razorevent.cxx.i

src/moc_razorevent.s: src/moc_razorevent.cxx.s
.PHONY : src/moc_razorevent.s

# target to generate assembly for a file
src/moc_razorevent.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorevent.cxx.s
.PHONY : src/moc_razorevent.cxx.s

src/moc_razorhandler.o: src/moc_razorhandler.cxx.o
.PHONY : src/moc_razorhandler.o

# target to build an object file
src/moc_razorhandler.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorhandler.cxx.o
.PHONY : src/moc_razorhandler.cxx.o

src/moc_razorhandler.i: src/moc_razorhandler.cxx.i
.PHONY : src/moc_razorhandler.i

# target to preprocess a source file
src/moc_razorhandler.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorhandler.cxx.i
.PHONY : src/moc_razorhandler.cxx.i

src/moc_razorhandler.s: src/moc_razorhandler.cxx.s
.PHONY : src/moc_razorhandler.s

# target to generate assembly for a file
src/moc_razorhandler.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorhandler.cxx.s
.PHONY : src/moc_razorhandler.cxx.s

src/moc_razorlogoutmenu.o: src/moc_razorlogoutmenu.cxx.o
.PHONY : src/moc_razorlogoutmenu.o

# target to build an object file
src/moc_razorlogoutmenu.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorlogoutmenu.cxx.o
.PHONY : src/moc_razorlogoutmenu.cxx.o

src/moc_razorlogoutmenu.i: src/moc_razorlogoutmenu.cxx.i
.PHONY : src/moc_razorlogoutmenu.i

# target to preprocess a source file
src/moc_razorlogoutmenu.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorlogoutmenu.cxx.i
.PHONY : src/moc_razorlogoutmenu.cxx.i

src/moc_razorlogoutmenu.s: src/moc_razorlogoutmenu.cxx.s
.PHONY : src/moc_razorlogoutmenu.s

# target to generate assembly for a file
src/moc_razorlogoutmenu.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorlogoutmenu.cxx.s
.PHONY : src/moc_razorlogoutmenu.cxx.s

src/moc_razormainmenu.o: src/moc_razormainmenu.cxx.o
.PHONY : src/moc_razormainmenu.o

# target to build an object file
src/moc_razormainmenu.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razormainmenu.cxx.o
.PHONY : src/moc_razormainmenu.cxx.o

src/moc_razormainmenu.i: src/moc_razormainmenu.cxx.i
.PHONY : src/moc_razormainmenu.i

# target to preprocess a source file
src/moc_razormainmenu.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razormainmenu.cxx.i
.PHONY : src/moc_razormainmenu.cxx.i

src/moc_razormainmenu.s: src/moc_razormainmenu.cxx.s
.PHONY : src/moc_razormainmenu.s

# target to generate assembly for a file
src/moc_razormainmenu.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razormainmenu.cxx.s
.PHONY : src/moc_razormainmenu.cxx.s

src/moc_razorspinbutton.o: src/moc_razorspinbutton.cxx.o
.PHONY : src/moc_razorspinbutton.o

# target to build an object file
src/moc_razorspinbutton.cxx.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorspinbutton.cxx.o
.PHONY : src/moc_razorspinbutton.cxx.o

src/moc_razorspinbutton.i: src/moc_razorspinbutton.cxx.i
.PHONY : src/moc_razorspinbutton.i

# target to preprocess a source file
src/moc_razorspinbutton.cxx.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorspinbutton.cxx.i
.PHONY : src/moc_razorspinbutton.cxx.i

src/moc_razorspinbutton.s: src/moc_razorspinbutton.cxx.s
.PHONY : src/moc_razorspinbutton.s

# target to generate assembly for a file
src/moc_razorspinbutton.cxx.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/moc_razorspinbutton.cxx.s
.PHONY : src/moc_razorspinbutton.cxx.s

src/razor.o: src/razor.cpp.o
.PHONY : src/razor.o

# target to build an object file
src/razor.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razor.cpp.o
.PHONY : src/razor.cpp.o

src/razor.i: src/razor.cpp.i
.PHONY : src/razor.i

# target to preprocess a source file
src/razor.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razor.cpp.i
.PHONY : src/razor.cpp.i

src/razor.s: src/razor.cpp.s
.PHONY : src/razor.s

# target to generate assembly for a file
src/razor.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razor.cpp.s
.PHONY : src/razor.cpp.s

src/razoraboutdlg.o: src/razoraboutdlg.cpp.o
.PHONY : src/razoraboutdlg.o

# target to build an object file
src/razoraboutdlg.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razoraboutdlg.cpp.o
.PHONY : src/razoraboutdlg.cpp.o

src/razoraboutdlg.i: src/razoraboutdlg.cpp.i
.PHONY : src/razoraboutdlg.i

# target to preprocess a source file
src/razoraboutdlg.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razoraboutdlg.cpp.i
.PHONY : src/razoraboutdlg.cpp.i

src/razoraboutdlg.s: src/razoraboutdlg.cpp.s
.PHONY : src/razoraboutdlg.s

# target to generate assembly for a file
src/razoraboutdlg.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razoraboutdlg.cpp.s
.PHONY : src/razoraboutdlg.cpp.s

src/razorbar.o: src/razorbar.cpp.o
.PHONY : src/razorbar.o

# target to build an object file
src/razorbar.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbar.cpp.o
.PHONY : src/razorbar.cpp.o

src/razorbar.i: src/razorbar.cpp.i
.PHONY : src/razorbar.i

# target to preprocess a source file
src/razorbar.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbar.cpp.i
.PHONY : src/razorbar.cpp.i

src/razorbar.s: src/razorbar.cpp.s
.PHONY : src/razorbar.s

# target to generate assembly for a file
src/razorbar.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbar.cpp.s
.PHONY : src/razorbar.cpp.s

src/razorbartask.o: src/razorbartask.cpp.o
.PHONY : src/razorbartask.o

# target to build an object file
src/razorbartask.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbartask.cpp.o
.PHONY : src/razorbartask.cpp.o

src/razorbartask.i: src/razorbartask.cpp.i
.PHONY : src/razorbartask.i

# target to preprocess a source file
src/razorbartask.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbartask.cpp.i
.PHONY : src/razorbartask.cpp.i

src/razorbartask.s: src/razorbartask.cpp.s
.PHONY : src/razorbartask.s

# target to generate assembly for a file
src/razorbartask.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorbartask.cpp.s
.PHONY : src/razorbartask.cpp.s

src/razorclock.o: src/razorclock.cpp.o
.PHONY : src/razorclock.o

# target to build an object file
src/razorclock.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorclock.cpp.o
.PHONY : src/razorclock.cpp.o

src/razorclock.i: src/razorclock.cpp.i
.PHONY : src/razorclock.i

# target to preprocess a source file
src/razorclock.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorclock.cpp.i
.PHONY : src/razorclock.cpp.i

src/razorclock.s: src/razorclock.cpp.s
.PHONY : src/razorclock.s

# target to generate assembly for a file
src/razorclock.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorclock.cpp.s
.PHONY : src/razorclock.cpp.s

src/razorcmd.o: src/razorcmd.cpp.o
.PHONY : src/razorcmd.o

# target to build an object file
src/razorcmd.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorcmd.cpp.o
.PHONY : src/razorcmd.cpp.o

src/razorcmd.i: src/razorcmd.cpp.i
.PHONY : src/razorcmd.i

# target to preprocess a source file
src/razorcmd.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorcmd.cpp.i
.PHONY : src/razorcmd.cpp.i

src/razorcmd.s: src/razorcmd.cpp.s
.PHONY : src/razorcmd.s

# target to generate assembly for a file
src/razorcmd.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorcmd.cpp.s
.PHONY : src/razorcmd.cpp.s

src/razordeskswitch.o: src/razordeskswitch.cpp.o
.PHONY : src/razordeskswitch.o

# target to build an object file
src/razordeskswitch.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razordeskswitch.cpp.o
.PHONY : src/razordeskswitch.cpp.o

src/razordeskswitch.i: src/razordeskswitch.cpp.i
.PHONY : src/razordeskswitch.i

# target to preprocess a source file
src/razordeskswitch.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razordeskswitch.cpp.i
.PHONY : src/razordeskswitch.cpp.i

src/razordeskswitch.s: src/razordeskswitch.cpp.s
.PHONY : src/razordeskswitch.s

# target to generate assembly for a file
src/razordeskswitch.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razordeskswitch.cpp.s
.PHONY : src/razordeskswitch.cpp.s

src/razorevent.o: src/razorevent.cpp.o
.PHONY : src/razorevent.o

# target to build an object file
src/razorevent.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorevent.cpp.o
.PHONY : src/razorevent.cpp.o

src/razorevent.i: src/razorevent.cpp.i
.PHONY : src/razorevent.i

# target to preprocess a source file
src/razorevent.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorevent.cpp.i
.PHONY : src/razorevent.cpp.i

src/razorevent.s: src/razorevent.cpp.s
.PHONY : src/razorevent.s

# target to generate assembly for a file
src/razorevent.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorevent.cpp.s
.PHONY : src/razorevent.cpp.s

src/razorgui.o: src/razorgui.cpp.o
.PHONY : src/razorgui.o

# target to build an object file
src/razorgui.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorgui.cpp.o
.PHONY : src/razorgui.cpp.o

src/razorgui.i: src/razorgui.cpp.i
.PHONY : src/razorgui.i

# target to preprocess a source file
src/razorgui.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorgui.cpp.i
.PHONY : src/razorgui.cpp.i

src/razorgui.s: src/razorgui.cpp.s
.PHONY : src/razorgui.s

# target to generate assembly for a file
src/razorgui.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorgui.cpp.s
.PHONY : src/razorgui.cpp.s

src/razorhandler.o: src/razorhandler.cpp.o
.PHONY : src/razorhandler.o

# target to build an object file
src/razorhandler.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorhandler.cpp.o
.PHONY : src/razorhandler.cpp.o

src/razorhandler.i: src/razorhandler.cpp.i
.PHONY : src/razorhandler.i

# target to preprocess a source file
src/razorhandler.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorhandler.cpp.i
.PHONY : src/razorhandler.cpp.i

src/razorhandler.s: src/razorhandler.cpp.s
.PHONY : src/razorhandler.s

# target to generate assembly for a file
src/razorhandler.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorhandler.cpp.s
.PHONY : src/razorhandler.cpp.s

src/razorlogoutmenu.o: src/razorlogoutmenu.cpp.o
.PHONY : src/razorlogoutmenu.o

# target to build an object file
src/razorlogoutmenu.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorlogoutmenu.cpp.o
.PHONY : src/razorlogoutmenu.cpp.o

src/razorlogoutmenu.i: src/razorlogoutmenu.cpp.i
.PHONY : src/razorlogoutmenu.i

# target to preprocess a source file
src/razorlogoutmenu.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorlogoutmenu.cpp.i
.PHONY : src/razorlogoutmenu.cpp.i

src/razorlogoutmenu.s: src/razorlogoutmenu.cpp.s
.PHONY : src/razorlogoutmenu.s

# target to generate assembly for a file
src/razorlogoutmenu.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorlogoutmenu.cpp.s
.PHONY : src/razorlogoutmenu.cpp.s

src/razormainmenu.o: src/razormainmenu.cpp.o
.PHONY : src/razormainmenu.o

# target to build an object file
src/razormainmenu.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razormainmenu.cpp.o
.PHONY : src/razormainmenu.cpp.o

src/razormainmenu.i: src/razormainmenu.cpp.i
.PHONY : src/razormainmenu.i

# target to preprocess a source file
src/razormainmenu.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razormainmenu.cpp.i
.PHONY : src/razormainmenu.cpp.i

src/razormainmenu.s: src/razormainmenu.cpp.s
.PHONY : src/razormainmenu.s

# target to generate assembly for a file
src/razormainmenu.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razormainmenu.cpp.s
.PHONY : src/razormainmenu.cpp.s

src/razorpluginmanager.o: src/razorpluginmanager.cpp.o
.PHONY : src/razorpluginmanager.o

# target to build an object file
src/razorpluginmanager.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorpluginmanager.cpp.o
.PHONY : src/razorpluginmanager.cpp.o

src/razorpluginmanager.i: src/razorpluginmanager.cpp.i
.PHONY : src/razorpluginmanager.i

# target to preprocess a source file
src/razorpluginmanager.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorpluginmanager.cpp.i
.PHONY : src/razorpluginmanager.cpp.i

src/razorpluginmanager.s: src/razorpluginmanager.cpp.s
.PHONY : src/razorpluginmanager.s

# target to generate assembly for a file
src/razorpluginmanager.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorpluginmanager.cpp.s
.PHONY : src/razorpluginmanager.cpp.s

src/razorspinbutton.o: src/razorspinbutton.cpp.o
.PHONY : src/razorspinbutton.o

# target to build an object file
src/razorspinbutton.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorspinbutton.cpp.o
.PHONY : src/razorspinbutton.cpp.o

src/razorspinbutton.i: src/razorspinbutton.cpp.i
.PHONY : src/razorspinbutton.i

# target to preprocess a source file
src/razorspinbutton.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorspinbutton.cpp.i
.PHONY : src/razorspinbutton.cpp.i

src/razorspinbutton.s: src/razorspinbutton.cpp.s
.PHONY : src/razorspinbutton.s

# target to generate assembly for a file
src/razorspinbutton.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razorspinbutton.cpp.s
.PHONY : src/razorspinbutton.cpp.s

src/razortask.o: src/razortask.cpp.o
.PHONY : src/razortask.o

# target to build an object file
src/razortask.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortask.cpp.o
.PHONY : src/razortask.cpp.o

src/razortask.i: src/razortask.cpp.i
.PHONY : src/razortask.i

# target to preprocess a source file
src/razortask.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortask.cpp.i
.PHONY : src/razortask.cpp.i

src/razortask.s: src/razortask.cpp.s
.PHONY : src/razortask.s

# target to generate assembly for a file
src/razortask.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortask.cpp.s
.PHONY : src/razortask.cpp.s

src/razortray.o: src/razortray.cpp.o
.PHONY : src/razortray.o

# target to build an object file
src/razortray.cpp.o:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortray.cpp.o
.PHONY : src/razortray.cpp.o

src/razortray.i: src/razortray.cpp.i
.PHONY : src/razortray.i

# target to preprocess a source file
src/razortray.cpp.i:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortray.cpp.i
.PHONY : src/razortray.cpp.i

src/razortray.s: src/razortray.cpp.s
.PHONY : src/razortray.s

# target to generate assembly for a file
src/razortray.cpp.s:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(MAKE) -f razorqt-panel/CMakeFiles/razor-panel.dir/build.make razorqt-panel/CMakeFiles/razor-panel.dir/src/razortray.cpp.s
.PHONY : src/razortray.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... razor-panel"
	@echo "... rebuild_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/moc_razorbar.o"
	@echo "... src/moc_razorbar.i"
	@echo "... src/moc_razorbar.s"
	@echo "... src/moc_razorbartask.o"
	@echo "... src/moc_razorbartask.i"
	@echo "... src/moc_razorbartask.s"
	@echo "... src/moc_razorclock.o"
	@echo "... src/moc_razorclock.i"
	@echo "... src/moc_razorclock.s"
	@echo "... src/moc_razorcmd.o"
	@echo "... src/moc_razorcmd.i"
	@echo "... src/moc_razorcmd.s"
	@echo "... src/moc_razordeskswitch.o"
	@echo "... src/moc_razordeskswitch.i"
	@echo "... src/moc_razordeskswitch.s"
	@echo "... src/moc_razorevent.o"
	@echo "... src/moc_razorevent.i"
	@echo "... src/moc_razorevent.s"
	@echo "... src/moc_razorhandler.o"
	@echo "... src/moc_razorhandler.i"
	@echo "... src/moc_razorhandler.s"
	@echo "... src/moc_razorlogoutmenu.o"
	@echo "... src/moc_razorlogoutmenu.i"
	@echo "... src/moc_razorlogoutmenu.s"
	@echo "... src/moc_razormainmenu.o"
	@echo "... src/moc_razormainmenu.i"
	@echo "... src/moc_razormainmenu.s"
	@echo "... src/moc_razorspinbutton.o"
	@echo "... src/moc_razorspinbutton.i"
	@echo "... src/moc_razorspinbutton.s"
	@echo "... src/razor.o"
	@echo "... src/razor.i"
	@echo "... src/razor.s"
	@echo "... src/razoraboutdlg.o"
	@echo "... src/razoraboutdlg.i"
	@echo "... src/razoraboutdlg.s"
	@echo "... src/razorbar.o"
	@echo "... src/razorbar.i"
	@echo "... src/razorbar.s"
	@echo "... src/razorbartask.o"
	@echo "... src/razorbartask.i"
	@echo "... src/razorbartask.s"
	@echo "... src/razorclock.o"
	@echo "... src/razorclock.i"
	@echo "... src/razorclock.s"
	@echo "... src/razorcmd.o"
	@echo "... src/razorcmd.i"
	@echo "... src/razorcmd.s"
	@echo "... src/razordeskswitch.o"
	@echo "... src/razordeskswitch.i"
	@echo "... src/razordeskswitch.s"
	@echo "... src/razorevent.o"
	@echo "... src/razorevent.i"
	@echo "... src/razorevent.s"
	@echo "... src/razorgui.o"
	@echo "... src/razorgui.i"
	@echo "... src/razorgui.s"
	@echo "... src/razorhandler.o"
	@echo "... src/razorhandler.i"
	@echo "... src/razorhandler.s"
	@echo "... src/razorlogoutmenu.o"
	@echo "... src/razorlogoutmenu.i"
	@echo "... src/razorlogoutmenu.s"
	@echo "... src/razormainmenu.o"
	@echo "... src/razormainmenu.i"
	@echo "... src/razormainmenu.s"
	@echo "... src/razorpluginmanager.o"
	@echo "... src/razorpluginmanager.i"
	@echo "... src/razorpluginmanager.s"
	@echo "... src/razorspinbutton.o"
	@echo "... src/razorspinbutton.i"
	@echo "... src/razorspinbutton.s"
	@echo "... src/razortask.o"
	@echo "... src/razortask.i"
	@echo "... src/razortask.s"
	@echo "... src/razortray.o"
	@echo "... src/razortray.i"
	@echo "... src/razortray.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /usr/home/vdop/projects/razor-release/razorqt-0.2-RC2/razorqt-modules && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

