#include <QApplication>
#include <QPushButton>
#include <QMap>
#include <QLabel>
#include <QPainter>
#include <QPalette>
#include <QCheckBox>
#include <QVariant>
#include <QCursor>
#include <QTextStream>
#include <QFile>
#include <QFileInfo>
#include <QColor>
#include <QBitmap>
#include <QImage>
#include <QPixmap>
#include <QMouseEvent>
#include <QWheelEvent>
#include <QResizeEvent>
#include <QHash>
#include <QSizePolicy>
#include <QToolButton>
#include <QAction>
#include <QVariant>
#include <QMenu>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>

#include <QtDBus/QDBusInterface>
#include <QtDBus/QDBusMessage>

#include <QIcon>
#include <QWidget>
#include <QSpinBox>
#include <QByteArray>
#include <QBrush>
#include <QFrame>
#include <QX11Info>
#include <QDesktopWidget>
#include <QDebug>
#include <QProcess>
#include <QDir>
#include <QDirIterator>
#include <QSettings>
#include <QTabWidget>
#include <QDirModel>
#include <QTreeView>
#include <QMessageBox>
#include <QStringList>
#include <QListWidget>
#include <QTreeWidget>
#include <QTableWidget>
#include <QSignalMapper>
#include <QFileDialog>
#include <QColorDialog>
#include <QGroupBox>
#include <QSpacerItem>
#include <QDialogButtonBox>
#include <QLineEdit>
#include <QTextEdit>
#include <QTimer>
#include <QDateTime>
#include <QStyleFactory>
#include <QToolBox>
#include <QComboBox>
#include <QRadioButton>
#include <QX11EmbedContainer>
#include <QX11EmbedWidget>
#include <QKeyEvent>
#include <QFileIconProvider>
#include <QCompleter>
#include <QTranslator>
#include <QLibraryInfo>
#include <QTextCodec>
#include <QByteArray>
#include <QSizeGrip>
#include <QStackedWidget>
#include <QSplitter>
#include <QRubberBand>
#include <QShortcut>
#include <QButtonGroup>
#include <QHeaderView>
#include <QFileSystemModel>
#include <QFontDatabase>
#include <QDockWidget>

#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
#include <X11/extensions/shape.h>



