.TH razorqt-config "1" "September 2012" "Razor\-qt\ 0.5.0" "Razor\-qt\ Settings Center"
.SH NAME
razorqt-config \- \fBRazor-qt\fR Settings Center for all related modules and applications
.SH SYNOPSIS
.B razorqt-config
.br
.SH DESCRIPTION
This application its a settings center of all environment related applications, and all 
config software instaled and registered by the \fBRazor\-qt\fR desktop environment.
.P
\fBRazor-qt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies, ships several core desktop components, all of which are optional:
.P
 * Panel
 * Desktop
 * Application launcher
 * Settings center \fI(this)\fR
 * Session handler
 * Polkit handler
 * SSH password access
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their names are self-descriptive.  They are usually not launched
by hand but automatically, when choosing a \fBRazor\-qt\fR session in the Display
Manager.
.P
.SH Razor-qt Settings Center related applications
.P
\fBRazor-qt\fR has various config applications:
.P
 * Mouse settings: (\fBrazor-config-mouse\fR)
 * Desktop settings: (\fBrazor-config-desktop\fR)
 * Appereance settings: (\fBrazor-config-appearance\fR)
 * Session settings: (\fBrazor-config-session\fR)
 * Notification settings: (\fBrazor-config-notificationd\fR)
.P
All of this also can be find in Settings or Preferences menu, please consult the respective manpages.
.SH "REPORTING BUGS"
Report bugs to https://github.com/Razor-qt/Razor-qt/issues
.SH "SEE ALSO"
\fBRazor-qt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface.  Razor-qt is also intended for less powerful machines. See:

.\" any module must refers to session app, for more info on start it
.P
 * Mouse settings: \fBrazor-config-mouse.1\fR
.P
 * Desktop settings: \fBrazor-config-desktop.1\fR
.P
 * Appereance settings: \fBrazor-config-appearance.1\fR
.P
 * Session settings: \fBrazor-config-session.1\fR
.P
 * Notification settings: \fBrazor-config-notificationd.1\fR
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBRazor-qt\fR project and VENENUX GNU/Linux but can be used by others.
