.TH razor-panel "1" "September 2012" "Razor\-qt\ 0.5.0" "Razor\-qt\ Module"
.SH NAME
razor-panel \- Module of Razor-qt: the faster and lighter QT Desktop Environment
.SH SYNOPSIS
.B razor-panel
.br
.SH DESCRIPTION
This module adds a panel to the desktop.
.P
.P
The \fBRazor-qt modules\fR are desktop independent tools, that do not accept option parsing, 
and operate as daemons for the local user for desktop specific operations. 
.P
\fBRazor-qt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies. As new project, already contains the key DE components
and can be used separately, not all of them need to be used at once:
.P
 * Panel \fI(this)\fR
 * Desktop
 * Application launcher
 * Settings center
 * Sessions
 * Polkit handler
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their name is self-descriptive.  They are usually not launched
by hand but automatically, when choosing a Razor\-Qt session in the Display
Manager.
.P
.SH BEHAVIOR
.P
The module can be run standard alone, and also autostarted at logon. show a bar panel 
by default in bottom of desktop. By right clickin over there show config setting options for 
each plugins and also panel itsefl.
.P
.SH AUTOSTART
.P
The module only are showed on \fBRazor-qt\fR desktop environment, but u can create an autostart action 
for u prefered desktop environment.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/Razor-qt/Razor-qt/issues
.SH "SEE ALSO"
\fBRazor-qt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface.  Razor-qt is also intended for less powerful machines. See:

.\" any module must refers to session app, for more info on start it
.P
\fBrazor-session.1\fR  Razor-qt for manage Razor-qt complete environment
.P
\fBstart-razor.1\fR  Razor-qt display management independient starup.
.P
\fBrazor-config.1\fR  Razor-qt config center application for performing settings
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBRazor-qt\fR project and VENENUX GNU/Linux but can be used by others.
